services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: devhoa
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped


  #    giao diện đồ họa người dùng host
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    # thiết lập biến môi trường
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order-service
      MYSQL_USER: devhoa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    ports:
      - "1234:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

# tập để lưu trữ dữ liệu
volumes:
  postgres:
  pgadmin:
  db_data:
    driver: local


