


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

# Identify routes
# Product Service Route
# Whenever a customer request in the path contains an api/product, then api gateway will route this specific request towards product-service
spring:
  cloud:
    gateway:
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/v1/products

      # Order Service Route
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/v1/order

      # Discovery Server Route
      routes[2]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/

      # Discovery Server Static Resource
      routes[3]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**


  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm